In [1]:
# import numpy 
import numpy as np

### Array

In [2]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [3]:
arr[0]

1

In [7]:
arr = np.array([1, 2, 3, 4, 5], dtype=float, ndmin=3)
arr

array([[[1., 2., 3., 4., 5.]]])

In [8]:
arr.ndim

3

In [9]:
arr = np.array([1, 2, 3, 4.5, '5.5'])
arr

array(['1', '2', '3', '4.5', '5.5'], dtype='<U32')

In [10]:
type(arr[0])

numpy.str_

In [11]:
arr = np.array([1, 2, 3, 4.5])
arr

array([1. , 2. , 3. , 4.5])

In [12]:
l = [1, 2, 3, 4, 5]
arr1 = np.asarray(l)
arr1

array([1, 2, 3, 4, 5])

In [13]:
arr1.min()

1

In [14]:
arr1.max()

5

In [15]:
arr.cumsum()

array([ 1. ,  3. ,  6. , 10.5])

In [19]:
arr = np.arange(0, 100, 10)
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [20]:
arr = np.arange(0, 100)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [23]:
arr.reshape(10, 10) # 10x10 = 100

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [24]:
arr.reshape(5, 20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [27]:
arr.reshape(20, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [29]:
arr.resize(10, 10)

In [30]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

### from functions

In [33]:
np.fromfunction(lambda x, y: x+y, (10, 5))

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 1.,  2.,  3.,  4.,  5.],
       [ 2.,  3.,  4.,  5.,  6.],
       [ 3.,  4.,  5.,  6.,  7.],
       [ 4.,  5.,  6.,  7.,  8.],
       [ 5.,  6.,  7.,  8.,  9.],
       [ 6.,  7.,  8.,  9., 10.],
       [ 7.,  8.,  9., 10., 11.],
       [ 8.,  9., 10., 11., 12.],
       [ 9., 10., 11., 12., 13.]])

In [38]:
np.fromfunction(lambda x, y: x==y, (5, 5))

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [39]:
i = (x for x in range(10))
np.fromiter(i, int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
s = "10, 20, 30, 40, 50, 60, 70, 80, 90, 100"
np.fromstring(s, sep=",", dtype=int)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### zeros and ones

In [47]:
arr = np.zeros(100)

In [48]:
arr.reshape(10, 10)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [46]:
np.zeros(100)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.,
       5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [52]:
np.ones((5, 2, 12), dtype=int)

array([[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]])

### random

In [54]:
np.random.rand(3, 3)

array([[0.96231416, 0.64931398, 0.11745921],
       [0.61145389, 0.23211846, 0.50443698],
       [0.68769282, 0.96044877, 0.11314326]])

In [55]:
np.random.randn(3, 3)

array([[ 1.94253751, -1.83298713,  0.04495852],
       [ 0.37451335, -0.22917259,  0.54101192],
       [ 1.27112042,  2.34161659, -0.34920579]])

In [85]:
np.random.randint(10, 100)

66

In [86]:
np.random.randint(10, 100, (10, 10))

array([[69, 45, 44, 12, 58, 26, 42, 30, 49, 58],
       [12, 95, 48, 57, 79, 69, 36, 71, 34, 73],
       [23, 98, 52, 96, 58, 32, 20, 86, 89, 49],
       [77, 22, 61, 27, 21, 37, 24, 60, 55, 91],
       [90, 45, 27, 58, 85, 11, 20, 67, 64, 51],
       [89, 38, 63, 65, 54, 47, 22, 38, 15, 46],
       [17, 70, 62, 49, 67, 23, 52, 29, 62, 30],
       [45, 50, 88, 64, 47, 31, 47, 17, 65, 57],
       [20, 31, 19, 49, 25, 18, 94, 45, 93, 98],
       [20, 88, 24, 97, 47, 66, 38, 55, 31, 81]])

### statics and math 

In [90]:
arr = np.random.randint(10,100,10)

In [91]:
arr

array([85, 43, 23, 28, 95, 91, 56, 77, 81, 30])

In [92]:
np.sin(arr)

array([-0.17607562, -0.83177474, -0.8462204 ,  0.27090579,  0.68326171,
        0.10598751, -0.521551  ,  0.99952016, -0.62988799, -0.98803162])

In [93]:
np.cos(arr)

array([-0.98437664,  0.5551133 , -0.53283302, -0.96260587,  0.73017356,
       -0.99436746,  0.85322011, -0.03097503,  0.77668598,  0.15425145])

In [94]:
np.tan(arr)

array([  0.17887017,  -1.49838734,   1.58815308,  -0.2814296 ,
         0.93575247,  -0.10658787,  -0.61127369, -32.26857578,
        -0.81099442,  -6.4053312 ])

In [95]:
np.pi

3.141592653589793

In [96]:
np.degrees(arr)

array([4870.14125861, 2463.71851906, 1317.8029288 , 1604.28182637,
       5443.09905374, 5213.91593569, 3208.56365273, 4411.77502251,
       4640.95814056, 1718.87338539])

In [97]:
np.min(arr)

23

In [98]:
np.max(arr)

95

In [105]:
np.percentile(arr,50)

66.5

In [104]:
np.mean(arr)

60.9

In [106]:
np.median(arr)

66.5

In [107]:
np.sort(arr)

array([23, 28, 30, 43, 56, 77, 81, 85, 91, 95])

In [108]:
np.average(arr)

60.9

In [109]:
np.std(arr)

26.703745055703326

In [110]:
np.var(arr)

713.0899999999999

In [111]:
np.sqrt(9)

3.0